drop database novatec;
create database novatec;
set datestyle to 'ISO,YMD';

\c novatec

create table if not exists adminuser (
	superuser varchar(50) not null,
	pass varchar (255) not null,
	constraint pk_adminuser primary key (superuser)
);

create table if not exists seller (
	cpf varchar(11) not null,
	sellername varchar(40) not null,
	dtbirth date not null,
	pccommision float not null,
	constraint pk_seller primary key (cpf)
);

create table if not exists sell (
	idsell int generated by default as identity ,
	descr varchar(50) not null,
	sellvalue float not null,
	mtdpayment int not null,
	sellercpf varchar(11) not null,
	dtcash date not null,
	constraint pk_sell primary key (idsell),
	constraint fk_sell_seller foreign key (sellercpf) references seller (cpf)
);
	

create table if not exists sellout(
	idout int generated by default as identity ,
	descr varchar(50) not null,
	outvalue float not null,
	sellercpf varchar(11) not null,
	dtcash date not null,
	constraint pk_sellout primary key(idout),
	constraint fk_sellout_seller foreign key (sellercpf) references seller (cpf)
);
	



insert into adminuser (superuser,pass) values ('Novatec','$2b$10$er1XHIhRoN9wvXx2YRkHM.OYWYuwoM5zaUdmym6oN3upyIl1FOx/S');
insert into seller (cpf,sellername,dtbirth,pccommision) values ('13047747712','Pedro Rosa','12-12-2000',3);
insert into sell (descr,sellvalue,mtdpayment,sellercpf,dtcash) values ('1 Mouse',22.00,1,'13047747712','2023-11-22');
insert into sellout (descr,outvalue,sellercpf,dtcash) values ('Almoço',24.00,'13047747712','2023-11-22');
