create database novatec;

\c novatec


create table if not exists cash (
	dtcash date not null, 
	constraint pk_cash primary key (dtcash)
);

create table if not exists seller (
	cpf varchar(11) not null,
	sellername varchar(40) not null,
	dtbirth date not null,
	pccommision float not null,
	constraint pk_seller primary key (cpf)
);

create table if not exists sell (
	idsell int generated by default as identity ,
	descr varchar(50) not null,
	sellvalue float not null,
	mtdpayment int not null,
	sellercpf varchar(11) not null,
	dtcash date not null,
	constraint pk_sell primary key (idsell),
	constraint fk_sell_seller foreign key (sellercpf) references seller (cpf),
	constraint fk_sell_cash foreign key (dtcash) references cash (dtcash)
);

create table if not exists sellout(
	idout int generated by default as identity ,
	descr varchar(50) not null,
	outvalue float not null,
	sellercpf varchar(11) not null,
	dtcash date not null,
	constraint pk_sellout primary key(idout),
	constraint fk_sellout_seller foreign key (sellercpf) references seller (cpf),
	constraint fk_sellout_cash foreign key (dtcash) references cash (dtcash)
);

create table if not exists shop (
	idshop int generated by default as identity,
	shopname varchar(50) not null,
	constraint pk_shop primary key (idshop)
);

insert into shop (shopname) values ('TestShop');
insert into seller (cpf,sellername,dtbirth,pccommision) values ('13047747712','Pedro Rosa','12-12-2000',3);
insert into cash (dtcash) values ('22-11-2023');
insert into sell (descr,sellvalue,mtdpayment,sellercpf,dtcash) values ('1 Mouse',22,1,'13047747712','22-11-2023');
