DROP DATABASE novatec;
CREATE DATABASE novatec;

\c novatec

CREATE TABLE if NOT EXISTS adminuser(
    cpf VARCHAR(11) NOT NULL,
    username VARCHAR (50) NOT NULL,
    adminpass VARCHAR (255) NOT NULL,
    CONSTRAINT pk_adminuser PRIMARY KEY (cpf)
);

CREATE TABLE if NOT EXISTS seller(
    sellercpf VARCHAR (11) NOT NULL,
    sellername VARCHAR (50) NOT NULL,
    sellerpass VARCHAR (255) NOT NULL,
    pccommision FLOAT NOT NULL,
    dtbirth DATE NOT NULL,
    CONSTRAINT pk_seller PRIMARY KEY (sellercpf)
);

CREATE TABLE if NOT EXISTS cash(
    dtcash DATE NOT NULL,
    change FLOAT NOT NULL,
    CONSTRAINT pk_cash PRIMARY KEY (dtcash)
);

CREATE TABLE if NOT EXISTS shop(
    shopname VARCHAR (50) NOT NULL,
    admincpf VARCHAR (50) NOT NULL,
    CONSTRAINT pk_shop PRIMARY KEY (shopname),
    CONSTRAINT fk_shop_adminuser FOREIGN KEY (admincpf) REFERENCES adminuser(cpf)
);

CREATE TABLE if NOT EXISTS sellerboard(
    sellercpf VARCHAR (11) NOT NULL,
    shopname VARCHAR (50),
    CONSTRAINT fk_sellerboard_seller FOREIGN KEY (sellercpf) REFERENCES seller(sellercpf),
    CONSTRAINT fk_sellerboard_shop FOREIGN KEY (shopname) REFERENCES shop(shopname)
);

CREATE TABLE if NOT EXISTS sell(
    idsell INT GENERATED BY DEFAULT AS IDENTITY,
    descr VARCHAR (50) NOT NULL,
    sellvalue FLOAT NOT NULL,
    mtdpayment INT NOT NULL,
    sellercpf VARCHAR (11) NOT NULL,
    dtcash DATE NOT NULL,
    CONSTRAINT  pk_sell PRIMARY KEY (idsell),
    CONSTRAINT fk_sell_seller FOREIGN KEY (sellercpf) REFERENCES seller(sellercpf),
    CONSTRAINT fk_sell_cash FOREIGN KEY (dtcash) REFERENCES cash(dtcash)
);

CREATE TABLE if NOT EXISTS sellout(
    idout INT GENERATED BY DEFAULT AS IDENTITY,
	descr VARCHAR(50) NOT NULL,
	outvalue float NOT NULL,
	sellercpf VARCHAR(11) NOT NULL,
    dtcash DATE NOT NULL,
    CONSTRAINT pk_sellout PRIMARY KEY (idout),
    CONSTRAINT fk_sellout_seller FOREIGN KEY (sellercpf) REFERENCES seller(sellercpf),
    CONSTRAINT fk_sellout_cash FOREIGN KEY (dtcash) REFERENCES cash(dtcash)
);

--INSERTS TESTS

INSERT INTO adminuser (cpf,username,adminpass) VALUES ('87823215266','Novatec','$2b$10$VvDnMc5hvZ8yPZVo.AJY7uofKDnNx/FSrsIQHdomiLyALRqznpMlu');
INSERT INTO seller VALUES ('13088888812','ryan','$2b$10$.1BNPKAjS7PKKla2czdMxufQzyfS6WHmjXTBPmJu9/6lEjpAY.I3S',5,'22-01-2000');
INSERT INTO seller VALUES ('19988823145','vitinho','$2b$10$zN2mzhTSCrE7NtSXhLJrAOPY65/u.TMTlJ4HBUnrpVLB7htK2.F.m',5,'10-01-1999');
INSERT INTO cash VALUES ('01-12-2023',250);
INSERT INTO cash VALUES ('30-11-2023',210);
insert into shop values('novatec','87823215266');
insert into sellerboard values ('13088888812','novatec');
insert into sellerboard values ('19988823145','novatec');
INSERT INTO sell (descr,sellvalue,mtdpayment,sellercpf,dtcash) values ('1 Mouse',35,1,'13088888812','01-12-2023');
INSERT INTO sell (descr,sellvalue,mtdpayment,sellercpf,dtcash) values ('1 Teclado',55,1,'19988823145','01-12-2023');
INSERT INTO sell (descr,sellvalue,mtdpayment,sellercpf,dtcash) values ('1 Carregador',25,1,'19988823145','30-11-2023');
INSERT INTO sellout (descr,outvalue,sellercpf,dtcash) values ('Pastel',15,'19988823145','01-12-2023');


